/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.93.0
  Forc version: 0.62.0
  Fuel-Core version: 0.31.0
*/

import type {
  BigNumberish,
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from "fuels";

export type AssetIdInput = { bits: string };
export type AssetIdOutput = AssetIdInput;

export interface PaymentAbiInterface extends Interface {
  functions: {
    transfer: FunctionFragment;
  };
}

export class PaymentAbi extends Contract {
  interface: PaymentAbiInterface;
  functions: {
    transfer: InvokeFunction<
      [
        amount_to_transfer: BigNumberish,
        asset_id: AssetIdInput,
        recipient: string,
      ],
      void
    >;
  };
}
