/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.93.0
  Forc version: 0.62.0
  Fuel-Core version: 0.31.0
*/

import type {
  BigNumberish,
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

export interface StoreAbiInterface extends Interface {
  functions: {
    get_value: FunctionFragment;
    set_value: FunctionFragment;
  };
}

export class StoreAbi extends Contract {
  interface: StoreAbiInterface;
  functions: {
    get_value: InvokeFunction<[], BN>;
    set_value: InvokeFunction<[value: BigNumberish], BN>;
  };
}
